name: The output returned
description: Github Action that returns 42 as output
author: 'Damian Mee <spam@meedamian.com>'

outputs:
  some-value:
    description: This is the output being returned
    value: 42

# The below doesn't matter at all
runs:
  using: docker
  image: "docker://alpine:latest"
  entrypoint: '["/bin/sh", "echo", "0"]'
