# src: https://help.github.com/en/articles/contexts-and-expression-syntax-for-github-actions#steps-context
#
#   `steps` should contain info about steps, including `output`s of previous steps, currently it doesn't
#

# Trigger on pushes to master as well as cron
on:
  push:
    branches:
      - master

  schedule:
    - cron: '0 3 * * *'

jobs:
  check-steps:
    name: Check if steps is properly populated
    runs-on: ubuntu-18.04
    steps:
        - uses: actions/checkout@v1.0.0

        - name: Run action that outputs output
          id: outputter
          uses: ./.github/actions/action-with-output

        - name: Check if `steps` is empty
          run: test $(echo "${{ toJson(steps) }}" | jq '. | length') -gt 0
