name: Trigger daily, and perform some tasks

on:
  schedule:
    - cron:  '*/5 * * * *'
#    - cron:  '0 8 * * *'

jobs:
  scheduled-run:
    name: Create, and push git tag
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1.0.0

      - name: Create and push new tag
        run: |
          cd "${GITHUB_WORKSPACE}" || exit 1

          git checkout -b master

          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

          git commit --allow-empty -m 'Nothing to see here.  Commited by trigger-daily.yml'

          REMOTE="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
          git push "${REMOTE}" master

          TAG="v0.0.1-$(date +%F)+$(echo ${GITHUB_SHA} | cut -c1-7)"

          echo "Creating and pushing: ${TAG}"
          git tag -a "${TAG}" -m "${TAG}"
          git push  "${REMOTE}"  "${TAG}"
