name: Should trigger on git tag push

on:
  push:
    tags:
      - v*

jobs:
  check-steps:
    name: Git tag job
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1.0.0

      - name: Print current ref
        run: echo ${{ GITHUB_REF }}

      - name: Check if it's an actual tag
        if: {{ !startsWith(github.ref, 'refs/tags/') }}
        run: exit 1
