# See: https://github.community/t5/GitHub-API-Development-and/How-to-restrict-execution-of-GitHub-Actions-workflow-on-tags/m-p/29567
# Workaround:
#
#  on:
#    push:
#      branches:
#        - refs/tags/*
#

on:
  push:
    tags:
      - '*'

jobs:
  check-steps:
    name: Should trigger on git tag push
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1.0.0

      - name: Print current ref
        run: echo ${GITHUB_REF}

      - name: "Check if it's an actual tag"
        run: |
          if [[ ${GITHUB_REF} != refs/tags/* ]]; then
            exit 1
          fi
